### ISSUE TITLE
endpoints for update

### ISSUE THREAD

**Issue by nikkimartin** [a161527/cs319-p2t5#106]
need endpoints to update the following:
- conferences
- events
- inventory (i think this actually is already in there)
- residence
- room set
- transportation (i would guess alex is taking care of this)

**Comment by brandonson** [comment]
I think there's a PUT endpoint for conference edit already (PUT `/api/conference/{confId}`), let me know if you need PATCH instead.

Just finished off the inventory endpoint (needed a bit of fixing) and it looks like there's a transportation one, so just have these left:

* event
* residence
* room set

**Comment by brandonson** [comment]
Finished in #113
