### ISSUE TITLE
endpoint for event permissions

### ISSUE THREAD

**Issue by nikkimartin** [a161527/cs319-p2t5#107]
need an endpoint to get event permissions (e.g. if someone can edit an event)

EDIT: Actually, now that I'm thinking of the context I want this in - what would be helpful is being able to pass in a conference id and getting a list of events back w/ their permissions.
for example:
$http.get('api/event/conference/1?includePermissions) would return something like
[{id: 1, name: 'event1', permissions: ['can-edit-event']}, {id: 2, name: 'event2', permissions: []]

or something like that

**Comment by brandonson** [comment]
Alright, will do that second one.
