### ISSUE TITLE
Dependent management endpoints

### ISSUE THREAD

**Issue by brandonson** [a161527/cs319-p2t5#26]
Basic dependent management endpoints.  No auditing included for this one.

Need the /api/accounts/{id}/dependents endpoint and any other related ones.  A few things that are obviously needed
- [x] /api/accounts/{id}/dependents - GET - List all dependents
- [x] /api/accounts/{id}/dependents - POST - Create a new dependent
- [ ] /api/accounts/{id}/dependents/{dep_id}/alter - POST - could have slightly different name, but this will change a dependent's info
- [x] /api/accounts/{id}/dependents/{dep_id} - DELETE - not sure whether we want this or a /remove POST, but this will remove the dependent.  Use POST if we want audits for this, DELETE otherwise.

**Comment by brandonson** [comment]
@a161527 was this something you were going to look at after you did the login/account creation stuff?

**Comment by a161527** [comment]
@brandonson 
I propose:

`PATCH api/accounts/{id}/dependents/{dep_id}`
instead of 
`POST api/accounts/{id}/dependents/{dep_id}/alter`

The PATCH request would be an array of proposed changes to the dependent with id={dep_id}

Thoughts?
