### ISSUE TITLE
email authentication throwing error

### ISSUE THREAD

**Issue by nikkimartin** [a161527/cs319-p2t5#42]
when checking if an email is valid, server returns an internal server error. screenshot attached.
![screenshot 70](https://cloud.githubusercontent.com/assets/3977773/13617153/0b1c0886-e532-11e5-9502-cb680ce84595.png)

**Comment by movingpylon** [comment]
Can you check out my branch and see if it works?

**Comment by nikkimartin** [comment]
issue with my .env

all fixed!
