### ISSUE TITLE
deletion endpoints

### ISSUE THREAD

**Issue by nikkimartin** [a161527/cs319-p2t5#89]
need deletion endpoints for:
- user
- conference
- event
- inventory
- residence
- room set
- transportation

**Comment by brandonson** [comment]
Pretty sure conference and user deletion exist (or did you mean account?)

Conference registration request deletion doesn't exist.

Inventory item deletion exists, but request rejection/deletion does not.

**Comment by brandonson** [comment]
[ ] account
[ ] conference registration request
[ ] event registration
[ ] inventory request
[ ] residence
[ ] room set
[ ] transportation

**Comment by brandonson** [comment]
@a161527 is transportation deletion going to be part of your stuff?

**Comment by nikkimartin** [comment]
@brandonson - still missing residence and room set deletion endpoints. just for reference, the routes i'm using, respectively, are 
- api/conferences/{confId}/residences/{resId}
- api/conferences/{confId}/residences/roomSets/{rsetId}

thanks
