### ISSUE TITLE
Cannot register for conference as a new user

### ISSUE THREAD

**Issue by XennMaestro** [a161527/cs319-p2t5#97]
Unable to register for a conference as a non-admin user.
-created a new account
-tried to register for event.
-no dependents or users show up.
-attempted to use select all option.
-Error was thrown.

**Comment by XennMaestro** [comment]
never mind issue was the user was not approved by admin.

**Comment by brandonson** [comment]
I think we should probably keep this open:
* Need to some how indicate that missing approval could be a cause
* Probably shouldn't be throwing out errors if they attempt to submit.

Though, when you say an error was thrown, what do you mean?

**Comment by XennMaestro** [comment]
-Basically if you have not been approved by by an admin you can go to the conference register button.
This takes you to the user selection page. however since you have not been approved no user show up. if you try to press next. it basically does nothing and throws and error saying no user selected.
-we could improve this by letting user know they are still in the administration queue.

**Comment by brandonson** [comment]
@nikkimartin Is this you, me, or both of us?  I don't think I do any checks for empty ID lists. Do I need to?

**Comment by nikkimartin** [comment]
fixed. it was giving an incorrect count for approved dependents. register button shouldn't show up at all for unapproved accounts now.
