### ISSUE TITLE
Cannot regiter for event after admin approves conference registration.

### ISSUE THREAD

**Issue by XennMaestro** [a161527/cs319-p2t5#98]
-Created a new user account.
-Approved the account using a different admin account.
-used the user account to register for a conference.
-used the admin account to approve user conference attend status.
-tried to register for event using user account.
-This took me to a select attendee page. but no users showed up on the list.
-So could not register for event.

**Comment by XennMaestro** [comment]
Its strange that it just accepts an empty page with no attendee selected. no error is thrown or confirmation message. so it is impossible to tell if a user has been registered or not. it simply takes you back to the previous page.

**Comment by nikkimartin** [comment]
fixed. was pulling wrong id.
